### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [mathix420/swap#1]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.1.2. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary swp -w /tmp/ext swp==0.1.2
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting swp==0.1.2
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/154/1f2de0a88e97d/swp-0.1.2.tar.gz (4.0 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-qv_71tmp/swp/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-qv_71tmp/swp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-qv_71tmp/swp/pip-egg-info
         cwd: /tmp/pip-wheel-qv_71tmp/swp/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-qv_71tmp/swp/setup.py", line 26, in <module>
        install_requires=open('requirements.txt').read().split('\n'),
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by mathix420** [comment]
Hi @thatch  !

Thank's for your issue, I have learned something !
I think I have fix the issue but I'm waiting for Pypi to propagate the new version to test it correctly.

PS: Really nice initiative your Pypi Bot !

**Comment by thatch** [comment]
It's only somewhat automated, but I confirmed 0.1.4 does fix the problem.  Thanks!
